### ISSUE TITLE
Add project: best-of-digital-identity

### ISSUE THREAD

**Issue by jruizaranguren** [best-of-lists/best-of#150]
**Project details:**

- Project Name: best-of-digital-identity
- Github URL: jruizaranguren/best-of-digital-identity
- Category: internet  
- License: Creative Commons
- Package Managers: 

**Additional context:**

I plan to add a new category for "internet". There are a lot of technologies and fields related to internet that could be of interest.

**Comment by jruizaranguren** [comment]
@LukasMasuch, What is left so the link can be shown in the Readme?

**Comment by LukasMasuch** [comment]
There was an issue in the project.yaml. I have fixed it and it should appear soon :)

**Comment by LukasMasuch** [comment]
Added now :)

**Comment by jruizaranguren** [comment]
Thanks!
