### ISSUE TITLE
Add project: best-of-mkdocs

### ISSUE THREAD

**Issue by pawamoy** [best-of-lists/best-of#88]
**Project details:**
I've just created a best-of list for MkDocs: https://github.com/pawamoy/best-of-mkdocs
Would you be interested in listing it in this very list? MkDocs is a static site generator written in Python (but language agnostic). It's great for technical documentation (particularly thanks to the Material for MkDocs theme).

- Project Name: best-of-mkdocs
- Github URL: https://github.com/pawamoy/best-of-mkdocs
- Category:  Development Tools?
- License:  Creative Commons
- Package Managers: none

**Additional context:**
Thanks for the best-of lists and generator, they're great :rocket:

**Comment by LukasMasuch** [comment]
Great list :) thanks for the contribution. I included it in this list!

**Comment by pawamoy** [comment]
Thank you! Yeah I really wanted to show complete descriptions, but then markers at the end would be pushed over next lines and it was not pretty. I was hoping to find Jinja templates involved in the rendering process, but didn't, so I went with manual re-formatting in Python. Glad you like it!

**Comment by LukasMasuch** [comment]
Yep, maybe adding a way to provide a template in the `projects.yaml` would be a good feature :) Btw. I also linked your list here: https://github.com/ml-tooling/best-of-python-dev#documentation

**Comment by pawamoy** [comment]
Thanks! Best-of lists are fantastic ^^
