### ISSUE TITLE
Add project: 

### ISSUE THREAD

**Issue by lyz-code** [best-of-lists/best-of#90]
**Project details:**

I've just created a best-of list for Digital Gardens: https://github.com/lyz-code/best-of-digital-gardens a collection of people documentation of what they learn. Would you be interested in listing it in this very list? 

- Project Name: Best of Digital Gardens
- Github URL: https://github.com/lyz-code/best-of-digital-gardens
- Category:  Documentation?
- License: Creative Commons
- Package Managers: none 

**Additional context:**
Thanks for the best-of lists and generator, they're great

**Comment by LukasMasuch** [comment]
Great list :) thanks for the contribution. I included it in this list!
